adminUser:
  password: vault:rom-dev/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: rverduci@cloudbees.com
  token: vault:rom-dev/pipelineUser:token
  username: core-platform-test-bot
prow:
  hmacToken: vault:rom-dev/prow:hmacToken
